### ISSUE TITLE
scanVcf error

### ISSUE THREAD

**Issue by SouzaBB** [parklab/SigMA#53] opened 2021-03-19 13:25 UTC
I'm trying to run SigMA on my VCF files collection but getting the following error:

`mtx <- make_matrix("/path/to/vcf_files/", file_type = 'vcf', ref_genome_name = 'hg19')`
`Erro: scanVcf: only "flag" INFO fields should have Number = 0 in the header; GROUP_ID is "character"`

Can someone provide some help on how to deal with that?

Also, I'm using msisensor2 to detect MSI signatures. Is it possible to use it's output as input for SigMA?

Thanks.

**Comment by dgulhan-bio** [comment] 2021-03-22 08:42
It seems like the vcf file format has an issue, you could try reformating the vcf files with a new header. The vcf files are read with VariantAnnotation packages readVcf function. You can directly test if the issue is in reading the vcf files by doing:

```
library('VariantAnnotation')
vcf <- readVcf(<path_to_file>)
```
If the above lines didn't work, this means the vcf file is not properly formatted. You can either convert them to a maf file or replace the vcf header (see below).

As a solution I can suggest you to replace the info lines of the vcf file with a new one. 
```
header_lines <- c('##fileformat=VCFv4.2\n',
'##FILTER=<ID=PASS,Description="All filters passed">\n',
'##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">\n',
'##FORMAT=<ID=AD,Number=G,Type=Integer,Description="Allelic Depths of REF and ALT(s) in the order listed">\n',
'##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">\n',
'##contig=<ID=1>\n',
'##contig=<ID=10>\n',
'##contig=<ID=11>\n',
'##contig=<ID=12>\n',
'##contig=<ID=13>\n',
'##contig=<ID=14>\n',
'##contig=<ID=15>\n',
'##contig=<ID=16>\n',
'##contig=<ID=17>\n',
'##contig=<ID=18>\n',
'##contig=<ID=19>\n',
'##contig=<ID=2>\n',
'##contig=<ID=20>\n',
'##contig=<ID=21>\n',
'##contig=<ID=22>\n',
'##contig=<ID=3>\n',
'##contig=<ID=4>\n',
'##contig=<ID=5>\n',
'##contig=<ID=6>\n',
'##contig=<ID=7>\n',
'##contig=<ID=8>\n',
'##contig=<ID=9>\n',
'##contig=<ID=X>\n',
'##contig=<ID=Y>\n',
'##INFO=<ID=VAF,Number=1,Type=Float,Description="VAF from mutect read filter if available">\n',
'##INFO=<ID=t_alt_count,Number=1,Type=Integer,Description="Tumour alt count from mutect read filter if available">\n',
'##INFO=<ID=t_ref_count,Number=1,Type=Integer,Description="Tumour reference count from mutect read filter if available">\n',
'##bcftools_viewVersion=1.3.1+htslib-1.3.1\n',
'#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\n')
```
In R you can loop over your files. For each file, read the file, extract the chromosome numbers, positions, reference and alternate allele info into `chroms`, `positions`, `refs`, `alts` arrays.  I cannot write a code for this as I don't know the format of the current files. Then for each file do the following:

```
sink(<reformatted_vcf_file_path>) # this is going to be your output file
for(line in header_lines){
  cat(line)
}
collapsed_muts <- paste0(chroms, '\t',
                          positions, '\t',
                          '.', '\t',
                          refs, '\t',
                          alts '\t',
                          '.', '\t',
                          '.', '\t',
                          '.','\n')
 cat(paste(collapsed_muts, collapse = ''))
 sink()
```

What is the sequencing platform you are using? I can give you more info about using the msisensor scores based on that.

**Comment by SouzaBB** [comment] 2021-03-22 11:50
Thank you very much for replying! For the header, I've found a simple `sed` solution for the problematic fields.

For the sequencing, I'm using Illumina's platform with Archer library prep. If you could plz, provide more info on how to use scores for this task!

Thanks

**Comment by dgulhan-bio** [comment] 2021-03-22 14:33
Please follow the wiki (Optimizing SigMA for your dataset) for training a new model Sig3 detection or selecting best model among existing ones and the thresholds to go with it:
https://github.com/parklab/SigMA/wiki
If you run into issues in the process please let me know.

The built-in MMRD models are limited to MSK-IMPACTS (~2Mb and > 1000 microsatellite loci) and WES data. If your panel size is much smaller than 2Mb, I can add a function so that you can optimize MMRD detection with MSISensor scores on your own. You can check the number of microsatellites covered by your panel reported as `Total_Number_of_Sites` by MSISensor algorithm. Please let me know.

Note: For Sig3 detection using built in models you should use `cosmic_catalog = 'v2'` in run() function. For using built-in MMRD models use `v3`. If you are training your own model you can use either.

**Comment by dgulhan-bio** [comment] 2021-04-16 08:45
I am closing this assuming the issue is resolved, please open a new issue if you have other questions.

**Closed as completed by dgulhan-bio** 2021-04-16 08:45 UTC
